### PR TITLE
ETPAND-9616: Android offline DASH playback support

### PR DESCRIPTION
**Pull request by armands-malejevs**
Add support for native DASH media source for offline playback.

### CODE REVIEW

**Review by ffelini — APPROVED** [review]
👍 LGTM (changes were duscussed with @armands-malejevs in offline)

**Review by rogercrunchyroll — APPROVED** [review]
lgtm.

**Review by gabriel-rivero — APPROVED** [review]
+1 nice, will this change be ported to the community project?

**Comment by armands-malejevs** [comment]
@gabriel-rivero I think that this would be a popular usecase so the effort to port it to the community project is not worth it.

**Pull request merged**
